kind: List
apiVersion: v1
items:
- kind: ReplicationController
  apiVersion: v1
  metadata:
    labels:
      app: nginx-rc-app
    name: nginx-rc
    namespace: default
  spec:
    replicas: 2
    selector:
      app: nginx-template
    template:
      metadata:
        labels:
          app: nginx-template
      spec:
        containers:
        - name: nginx-container
          image: nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            protocol: TCP
          args:
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 30
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: nginx-svc-app
    name: nginx-service
    namespace: default 
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
    selector:
      app: nginx-template
