#!/bin/bash
#
# hostfile must contain IP adress of master-centos & minion-centos
echo $(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)  centos-master >> /etc/hosts

echo "PS1='[\u@\h ] MASTER \$ '" >> /root/.bashrc
echo "PS1='[\u@\h ] MASTER \$ '" >> /home/centos/.bashrc

# get the latest updates
yum -y update

systemctl stop firewalld
systemctl disable firewalld

# Install and start ntp
yum -y install ntp
systemctl start ntpd
systemctl enable ntpd

# Install some tools
yum -y install git wget net-tools telnet vim mlocate
updatedb

#get the git files
mkdir /git
cd /git
git clone https://github.com/stackbuilder/kubernetes-workshop
git clone https://github.com/stickerlabs/kubernetes-centos
git clone https://github.com/kubernetes/kubernetes

cat << EOF > /etc/yum.repos.d/virt7-docker-common-release.repo
[virt7-docker-common-release]
name=virt7-docker-common-release
baseurl=http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/
gpgcheck=0
EOF

yum -y install --enablerepo=virt7-docker-common-release etcd kubernetes flannel

cp -f /etc/kubernetes/config /etc/kubernetes/config.original
cp -f /etc/etcd/etcd.conf /etc/etcd/etcd.conf.orginal
cp -f /etc/sysconfig/flanneld /etc/sysconfig/flanneld.orginal
cp -f /etc/kubernetes/apiserver /etc/kubernetes/apiserver.orginal

/usr/bin/cp -f /git/kubernetes-centos/master/conf/etcd.conf /etc/etcd/etcd.conf
/usr/bin/cp -f /git/kubernetes-centos/master/conf/flanneld /etc/sysconfig/flanneld
/usr/bin/cp -f /git/kubernetes-centos/master/conf/apiserver /etc/kubernetes/apiserver
/usr/bin/cp -f /git/kubernetes-centos/master/conf/config /etc/kubernetes/config
/usr/bin/cp -rf /git/kubernetes-centos/master/pods /root/

for SERVICES in etcd kube-apiserver kube-controller-manager kube-scheduler; do
    systemctl restart $SERVICES
    systemctl enable $SERVICES
    systemctl status $SERVICES 
done

etcdctl mk /coreos.com/network/config '{"Network":"172.17.0.0/16"}'

for SERVICES in flanneld; do
    systemctl restart $SERVICES
    systemctl enable $SERVICES
    systemctl status $SERVICES 
done

