#!/bin/bash
#
# hostfile must contain IP adress of master-centos & minion-centos
echo $(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)  centos-minion >> /etc/hosts# .bashrc

echo "PS1='[\u@\h ] MINION \$ '" >> /root/.bashrc
echo "PS1='[\u@\h ] MINION \$ '" >> /home/centos/.bashrc

yum -y update

systemctl stop firewalld
systemctl disable firewalld

# Install and start ntp
yum -y install ntp
systemctl start ntpd
systemctl enable ntpd

# Install some tools
yum -y install git net-tools telnet vim mlocate
updatedb

#get the git files
mkdir /git
cd /git
git clone https://github.com/stackbuilder/kubernetes-workshop
git clone https://github.com/stickerlabs/kubernetes-centos
git clone https://github.com/kubernetes/kubernetes

cat << EOF > /etc/yum.repos.d/virt7-docker-common-release.repo
[virt7-docker-common-release]
name=virt7-docker-common-release
baseurl=http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/
gpgcheck=0
EOF

yum -y install --enablerepo=virt7-docker-common-release kubernetes flannel

/usr/bin/cp -f /etc/kubernetes/config /etc/kubernetes/config.original
/usr/bin/cp -f /etc/sysconfig/flanneld /etc/sysconfig/flanneld.orginal
/usr/bin/cp -f /etc/kubernetes/kubelet /etc/kubernetes/kubelet.original


/usr/bin/cp -f /git/kubernetes-centos/master/conf/flanneld /etc/sysconfig/flanneld
/usr/bin/cp -f /git/kubernetes-centos/master/conf/config /etc/kubernetes/config
/usr/bin/cp -f /git/kubernetes-centos/minion/conf/kubelet /etc/kubernetes/kubelet
/usr/bin/cp -f /git/kubernetes-centos/minion/manual-install /root/manual-install


for SERVICES in flanneld kube-proxy kubelet docker; do
    systemctl restart $SERVICES
    systemctl enable $SERVICES
    systemctl status $SERVICES 
done


